version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:4
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - restore_cache:
          key: node-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn run build
      - run: yarn test
      - save_cache:
          key: node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
